'''
Mapping previously used country names to ISO-3166 alpha-2 codes
'''

COUNTRY_CODE_MAPPING = {
 'Afghanistan': 'AF',
 'Albania': 'AL',
 'Algeria': 'DZ',
 'American_Samoa': 'AS',
 'Andorra': 'AD',
 'Angola': 'AO',
 'Anguilla': 'AI',
 'Antarctica': 'AQ',
 'Antigua and Barbuda': 'AG',
 'Argentina': 'AR',
 'Armenia': 'AM',
 'Aruba': 'AW',
 'Australia': 'AU',
 'Austria': 'AT',
 'Azerbaijan': 'AZ',
 'Bahamas, The': 'BS',
 'Bahrain': 'BH',
 'Bangladesh': 'BD',
 'Barbados': 'BB',
 'Belarus': 'BY',
 'Belgium': 'BE',
 'Belize': 'BZ',
 'Benin': 'BJ',
 'Bermuda': 'BM',
 'Bhutan': 'BT',
 'Bolivia': 'BO',
 'Bosnia and Herzegovina': 'BA',
 'Botswana': 'BW',
 'Brazil': 'BR',
 'Brunei Darussalam': 'BN',
 'Bulgaria': 'BG',
 'Burkina Faso': 'BF',
 'Burundi': 'BI',
 'Cambodia': 'KH',
 'Cameroon': 'CM',
 'Canada': 'CA',
 'Cape Verde': 'CV',
 'Cayman Islands': 'KY',
 'Central African Republic': 'CF',
 'Chad': 'TD',
 'Channel Islands': '',
 'Chile': 'CL',
 'China': 'CN',
 'Christmas Island': 'CX',
 'Cocos Islands': 'CC',
 'Colombia': 'CO',
 'Comoros': 'KM',
 'Congo, Dem. Rep.': 'CD',
 'Democratic Rep of Congo': 'CD',
 'Democratic Republic of the Congo': 'CD',
 'Congo, Republic': 'CG',
 'Republic of the Congo': 'CG',
 'Cook_Islands': 'CK',
 'Costa Rica': 'CR',
 "Cote d'Ivoire": 'CI',
 'Croatia': 'HR',
 'Cuba': 'CU',
 'Cyprus': 'CY',
 'Czech Republic': 'CZ',
 'Denmark': 'DK',
 "Democratic People's Republic of Korea": 'KP',
 "North Korea": 'KP',
 'Djibouti': 'DJ',
 'Dominica': 'DM',
 'Dominican Republic': 'DO',
 'Ecuador': 'EC',
 'Egypt': 'EG',
 'Egypt, Arab Rep.': 'EG',
 'El Salvador': 'SV',
 'Equatorial Guinea': 'GQ',
 'Eritrea': 'ER',
 'Erythrea': 'ER',
 'Estonia': 'EE',
 'Ethiopia': 'ET',
 'Falkland Islands': 'FK',
 'Fiji': 'FJ',
 'Finland': 'FI',
 'France': 'FR',
 'French Guiana': 'GF',
 'French Polynesia': 'PF',
 'French_Polynesia': 'PF',
 'Gabon': 'GA',
 'Gambia': 'GA',
 'Gambia, The': 'GM',
 'Georgia': 'GE',
 'Germany': 'DE',
 'Ghana': 'GH',
 'Gibraltar': 'GI',
 'Greece': 'GR',
 'Greenland': 'GL',
 'Grenada': 'GD',
 'Guadeloupe': 'GP',
 'Guam': 'GU',
 'Guatemala': 'GT',
 'Guinea': 'GN',
 'Guinea-Bissau': 'GW',
 'Guyana': 'GY',
 'Haiti': 'HT',
 'Honduras': 'HN',
 'Hong Kong': 'HK',
 'Hungary': 'HU',
 'Iceland': 'IS',
 'India': 'IN',
 'Indonesia': 'ID',
 'Iraq': 'IQ',
 'Iran': 'IR',
 'Iran, Islamic Rep.': 'IR',
 'Ireland': 'IE',
 'Israel': 'IL',
 'Italy': 'IT',
 'Jamaica': 'JM',
 'Japan': 'JP',
 'Johnston_Island': 'JT',
 'Jordan': 'JO',
 'Kazakhstan': 'KZ',
 'Kenya': 'KE',
 'Kiribati': 'KI',
 'Kuwait': 'KW',
 'Kyrgyzstan': 'KG',
 "Laos": 'LA',
 "Lao People's Democratic Republic": 'LA',
 'Latvia': 'LV',
 'Lebanon': 'LB',
 'Lesotho': 'LS',
 'Liberia': 'LR',
 'Libya': 'LY',
 'Lithuania': 'LT',
 'Luxembourg': 'LU',
 'Macao SAR, China': 'MO',
 'Macau': 'MO',
 'Macedonia': 'MK',
 'Macedonia, Former Yugoslav Republic of': 'MK',
 'Madagascar': 'MG',
 'Malawi': 'MW',
 'Malaysia': 'MY',
 'Maldives': 'MV',
 'Mali': 'ML',
 'Malta': 'MT',
 'Marshall Islands': 'MH',
 'Martinique': 'MQ',
 'Mauritania': 'MR',
 'Mauritius': 'MU',
 'Mayotte': 'YT',
 'Mexico': 'MX',
 'Micronesia, Federated States of': 'FM',
 'Moldova': 'MD',
 'Monaco': 'MC',
 'Mongolia': 'MN',
 'Morocco': 'MA',
 'Mozambique': 'MZ',
 'Myanmar': 'MM',
 'Namibia': 'NA',
 'Naur': 'NR',
 'Nepal': 'NP',
 'Netherlands': 'NL',
 'Neth_Antilles': 'AN',
 'New Caledonia': 'NC',
 'New_Caledonia': 'NC',
 'New Zealand': 'NZ',
 'Northern_Mariana_Islands': 'MP',
 'Nicaragua': 'NI',
 'Niger': 'NE',
 'Nigeria': 'NG',
 'Niue': 'NU',
 'Norfolk Island': 'NF',
 'Norway': 'NO',
 'Oman': 'OM',
 'Pakistan': 'PK',
 'Palau': 'PW',
 'Palestinian Authority': 'PS',
 'West Bank': 'PS',
 'Panama': 'PA',
 'Papua New Guinea': 'PG',
 'Paraguay': 'PY',
 'Peru': 'PE',
 'Philippines': 'PH',
 'Poland': 'PL',
 'Portugal': 'PT',
 'Puerto Rico': 'PR',
 'Qatar': 'QA',
 'Republic of Korea': 'KR',
 'South Korea': 'KR',
 'Reunion': 'RE',
 'Romania': 'RO',
 'Russia': 'RU',
 'Rwanda': 'RW',
 'Saint Pierre and Miquelon': 'PM',
 'St. Vincent and the Grenadines': 'VC',
 'Samoa': 'WS',
 'Sao Tome and Principe': 'ST',
 'Saudi Arabia': 'SA',
 'Senegal': 'SN',
 'Serbia': 'RS',
 'Seychelles': 'SC',
 'Sierra Leone': 'SL',
 'Singapore': 'SG',
 'Slovakia': 'SK',
 'Slovenia': 'SI',
 'Solomon_Islands': 'SB',
 'Somalia': 'SO',
 'South Africa': 'ZA',
 'South Sudan': 'SS',
 'Spain': 'ES',
 'Sri Lanka': 'LK',
 'St. Helena': 'SH',
 'St. Kitts and Nevis': 'KN',
 'St. Lucia': 'LC',
 'Sudan': 'SD',
 'Suriname': 'SR',
 'Swaziland': 'SZ',
 'Sweden': 'SE',
 'Switzerland': 'CH',
 'Syria': 'SY',
 'Syrian Arab Republic': 'SY',
 'Taiwan': 'TW',
 'Tajikistan': 'TJ',
 'Tanzania': 'TZ',
 'Thailand': 'TH',
 'Togo': 'TG',
 'Tonga': 'TO',
 'Trinidad and Tobago': 'TT',
 'Tunisia': 'TN',
 'Turkey': 'TR',
 'Turkmenistan': 'TM',
 'Turks and Caicos Islands': 'TC',
 'Tuval': 'TV',
 'Uganda': 'UG',
 'Ukraine': 'UA',
 'United Arab Emirates': 'AE',
 'United Kingdom': 'GB',
 'U.S.': 'US',
 'United States': 'US',
 'Uruguay': 'UY',
 'Uzbekistan': 'UZ',
 'Vanuatu': 'VU',
 'Venezuela': 'VE',
 'Vietnam': 'VN',
 'Virgin Islands, U.K.': 'VG',
 'Virgin Islands, U.S.': 'VI',
 'Wallis_&_Futuna_Is': 'WF',
 'Western Sahara': 'EH',
 'Yemen': 'YE',
 'Yemen, Rep.': 'YE',
 'Zambia': 'ZM',
 'Zimbabwe': 'ZW'}
