LANG_TO_COUNTRIES = {
 'af': {'Namibia': 4.4, 'South Africa': 13.35},
 'am': {'Ethiopia': 32.7},
 'ar': {'Algeria': 73,
        'Australia': 1.2,
        'Bahrain': 100,
        'Chad': 50,
        'Comoros': 100,
        'Djibouti': 50,
        'Egypt, Arab Rep.': 100,
        'Eritrea': 70,
        'Ethiopia': 7.5,
        'Iran, Islamic Rep.': 5,
        'Iraq': 80,
        'Israel': 20,
        'Jordan': 100,
        'Kuwait': 50,
        'Lebanon': 100,
        'Libya': 90,
        'Mauritania': 100,
        'Morocco': 100,
        'Oman': 100,
        'Palestinian Authority': 100,
        'Qatar': 50,
        'Saudi Arabia': 100,
        'Somalia': 10,
        'South Sudan': 50,
        'Sudan': 50,
        'Syrian Arab Republic': 100,
        'Tunisia': 100,
        'Turkey': 1.2,
        'United Arab Emirates': 100,
        'Western Sahara': 100,
        'Yemen, Rep.': 100},
 'ay': {'Bolivia': 14.6},
 'az': {'Azerbaijan': 90.3},
 'be': {'Belarus': 36.7},
 'bg': {'Bulgaria': 84.5, 'Moldova': 1.14},
 'bm': {'Mali': 80},
 'bn': {'Bangladesh': 98, 'India': 8.1},
 'ca': {'Andorra': 50, 'Spain': 17},
 'ch': {'Guam': 22.2},
 'cs': {'Czech Republic': 100},
 'cy': {'United Kingdom': 1.2},
 'da': {'Denmark': 100, 'Faeroe Islands': 100, 'Greenland': 13.7},
 'de': {'Austria': 88.6,
        'Germany': 100,
        'Luxembourg': 4,
        'Namibia': 32,
        'Switzerland': 66.7},
 'dv': {'Maldives': 95},
 'el': {'Australia': 1.3, 'Cyprus': 50, 'Greece': 100},
 'en': {'American_Samoa': 2.9,
        'Anguilla': 100,
        'Antigua and Barbuda': 100,
        'Aruba': 7.7,
        'Australia': 78.5,
        'Bahamas, The': 100,
        'Bangladesh': 2,
        'Barbados': 100,
        'Belize': 3.9,
        'Bermuda': 91.8,
        'Botswana': 2.1,
        'Brunei Darussalam': 20,
        'Cambodia': 2.5,
        'Cameroon': 50,
        'Canada': 65,
        'Cayman Islands': 95,
        'Channel Islands': 100,
        'Chile': 100,
        'Dominica': 100,
        'Eritrea': 30,
        'Ethiopia': 7.5,
        'Falkland Islands': 100,
        'Fiji': 50,
        'Gambia, The': 100,
        'Ghana': 100,
        'Gibraltar': 100,
        'Grenada': 100,
        'Guam': 38.3,
        'Guyana': 100,
        'Hong Kong': 2.8,
        'Ireland': 95,
        'Jamaica': 100,
        'Kenya': 20,
        'Kuwait': 50,
        'Lesotho': 10,
        'Liberia': 20,
        'Libya': 5,
        'Luxembourg': 1,
        'Macao SAR, China': 1.5,
        'Malawi': 100,
        'Maldives': 5,
        'Malta': 6,
        'Marshall Islands': 100,
        'Mauritius': 1,
        'Micronesia, Federated States of': 100,
        'Namibia': 7,
        'New Zealand': 91.2,
        'Nigeria': 100,
        'Norfolk Island': 100,
        'Palau': 9.4,
        'Panama': 14,
        'Papua New Guinea': 1,
        'Philippines': 4,
        'Puerto Rico': 2.5,
        'Qatar': 50,
        'Rwanda': 20,
        'Seychelles': 5,
        'Sierra Leone': 100,
        'Singapore': 23,
        'Solomon_Islands': 2,
        'Somalia': 5,
        'South Africa': 8.2,
        'South Sudan': 50,
        'St. Helena': 100,
        'St. Kitts and Nevis': 100,
        'St. Lucia': 100,
        'St. Vincent and the Grenadines': 100,
        'Sudan': 50,
        'Swaziland': 100,
        'Switzerland': 1,
        'Tanzania': 10,
        'Trinidad and Tobago': 100,
        'Turks and Caicos Islands': 100,
        'Uganda': 20,
        'United Kingdom': 96.3,
        'United States': 82.1,
        'Vanuatu': 2,
        'Virgin Islands, U.S.': 74.7,
        'Zambia': 1.7,
        'Zimbabwe': 100},
 'es': {'Andorra': 40,
        'Argentina': 85,
        'Aruba': 12.6,
        'Belize': 46,
        'Bolivia': 60.7,
        'Cayman Islands': 5,
        'Colombia': 100,
        'Costa Rica': 100,
        'Cuba': 100,
        'Dominican Republic': 100,
        'Ecuador': 100,
        'El Salvador': 100,
        'Equatorial Guinea': 75,
        'Guatemala': 100,
        'Honduras': 100,
        'Mexico': 100,
        'Nicaragua': 97.5,
        'Panama': 86,
        'Paraguay': 3.1,
        'Peru': 84.1,
        'Puerto Rico': 87,
        'Spain': 74,
        'United States': 10.7,
        'Uruguay': 100,
        'Venezuela': 100,
        'Virgin Islands, U.S.': 16.8},
 'et': {'Estonia': 70},
 'eu': {'Spain': 2},
 'fa': {'Afghanistan': 50, 'Iran, Islamic Rep.': 75},
 'fi': {'Finland': 95},
 'fil': {'Guam': 22.2,
         'Macao SAR, China': 1.3,
         'Palau': 13.5,
         'Philippines': 55},
 'fr': {'Algeria': 5,
        'Andorra': 10,
        'Belgium': 40,
        'Benin': 40,
        'Burkina Faso': 100,
        'Burundi': 0.02,
        'Cambodia': 2.5,
        'Cameroon': 50,
        'Canada': 35,
        'Central African Republic': 100,
        'Chad': 50,
        'Congo, Dem. Rep.': 100,
        'Congo, Republic': 100,
        "Cote d'Ivoire": 100,
        'Cyprus': 50,
        'Djibouti': 50,
        'Equatorial Guinea': 25,
        'France': 100,
        'French Guiana': 100,
        'French_Polynesia': 61.1,
        'Gabon': 100,
        'Guinea': 100,
        'Haiti': 25.2,
        'Luxembourg': 6,
        'Madagascar': 100,
        'Martinique': 100,
        'Mauritius': 3.5,
        'Mayotte': 100,
        'New_Caledonia': 100,
        'Niger': 100,
        'Reunion': 100,
        'Rwanda': 20,
        'Saint Pierre and Miquelon': 100,
        'Senegal': 100,
        'Switzerland': 23.4,
        'Togo': 100,
        'Virgin Islands, U.S.': 6.6,
        'Wallis_&_Futuna_Is': 10.8},
 'ga': {'Ireland': 5},
 'gd': {'United Kingdom': 2.5},
 'gl': {'Spain': 7},
 'he': {'Israel': 80},
 'hi': {'Fiji': 50, 'India': 41},
 'hr-sr': {'Austria': 2.2,
           'Bosnia and Herzegovina': 33.2,
           'Croatia': 100,
           'Serbia': 95},
 'ht': {'Belize': 32.9, 'Haiti': 74.8, 'Mauritius': 80.5, 'Seychelles': 95},
 'hu': {'Hungary': 93.6, 'Romania': 6.7, 'Serbia': 5, 'Slovakia': 10},
 'hy': {'Armenia': 97.7, 'Azerbaijan': 1.5, 'Georgia': 10},
 'id-ms': {'Brunei Darussalam': 80,
           'Indonesia': 100,
           'Malaysia': 100,
           'Singapore': 14.1},
 'is': {'Iceland': 100},
 'it': {'Argentina': 3.8,
        'Australia': 1.6,
        'Italy': 100,
        'Libya': 5,
        'Somalia': 5,
        'Switzerland': 8.9},
 'ja': {'Japan': 100, 'Palau': 1.5},
 'ka': {'Georgia': 80},
 'kk': {'Kazakhstan': 60},
 'km': {'Cambodia': 95},
 'ko': {"Democratic People's Republic of Korea": 100,
        'Republic of Korea': 100},
 'ku': {'Iran, Islamic Rep.': 20, 'Iraq': 20, 'Turkey': 6},
 'ky': {'Kyrgyzstan': 64.7},
 'lb': {'Luxembourg': 77},
 'lo': {"Lao People's Democratic Republic": 100},
 'lt': {'Latvia': 4.3, 'Lithuania': 80},
 'lv': {'Latvia': 58.2},
 'mk': {'Macedonia, Former Yugoslav Republic of': 66.5},
 'ml': {'India': 3.2},
 'mn': {'Mongolia': 100},
 'mr': {'India': 7},
 'mt': {'Malta': 90.2},
 'my': {'Myanmar': 66.7},
 'nb': {'Norway': 100},
 'nl': {'Aruba': 5.8, 'Belgium': 60, 'Netherlands': 100, 'Suriname': 100},
 'nso': {'South Africa': 9.39},
 'om': {'Ethiopia': 31.6},
 'pa': {'India': 2.8, 'Pakistan': 48},
 'pl': {'Lithuania': 10, 'Poland': 97.8},
 'pt': {'Angola': 80,
        'Bermuda': 4,
        'Brazil': 100,
        'Cape Verde': 100,
        'Guinea-Bissau': 100,
        'Mozambique': 10.7,
        'Portugal': 100,
        'Sao Tome and Principe': 100},
 'qu': {'Bolivia': 21.2},
 'ro': {'Albania': 5, 'Moldova': 75.17, 'Romania': 91},
 'ru': {'Armenia': 0.9,
        'Azerbaijan': 1.8,
        'Belarus': 62.8,
        'Estonia': 30,
        'Georgia': 10,
        'Kazakhstan': 40,
        'Kyrgyzstan': 12.5,
        'Latvia': 37.5,
        'Lithuania': 10,
        'Moldova': 15.99,
        'Russia': 100,
        'Turkmenistan': 12,
        'Ukraine': 24,
        'Uzbekistan': 14.2},
 'si': {'Sri Lanka': 74},
 'sk': {'Slovakia': 90},
 'sl': {'Slovenia': 100},
 'so': {'Somalia': 80},
 'sq': {'Albania': 95, 'Macedonia, Former Yugoslav Republic of': 25.1},
 'sv': {'Finland': 5, 'Sweden': 100},
 'sw': {'Kenya': 80, 'Tanzania': 90, 'Uganda': 80},
 'ta': {'India': 5.9, 'Sri Lanka': 18},
 'te': {'India': 7.2},
 'tg': {'Tajikistan': 100, 'Uzbekistan': 4.4},
 'th': {'Thailand': 100},
 'tk': {'Turkmenistan': 72},
 'tr': {'Austria': 2.3,
        'Bulgaria': 9.6,
        'Macedonia, Former Yugoslav Republic of': 8.4,
        'Turkey': 90},
 'uk': {'Moldova': 3.85, 'Ukraine': 67},
 'ur': {'India': 5, 'Pakistan': 8},
 'uz': {'Kyrgyzstan': 13.6, 'Turkmenistan': 9, 'Uzbekistan': 74.3},
 'vi': {'Vietnam': 100},
 'xh': {'South Africa': 17.64},
 'zh-zh-TW': {'Australia': 2.5,
              'China': 100,
              'Hong Kong': 91.7,
              'Macao SAR, China': 97,
              'Palau': 5.7,
              'Singapore': 40.7,
              'Taiwan': 100},
 'zu': {'South Africa': 23.83}}
